### PR TITLE
chore: use s3 as state backend

### PR DESCRIPTION
**Pull request by frezbo**
Use s3 as state backend.

### CODE REVIEW

**Comment by TimJones** [comment]
Are we actually consuming these as modules somewhere? I assumed since they were examples they should be *minimal* and not implement this, leaving it rather up to the user.

**Comment by frezbo** [comment]
also this is not part of tf code the user see, `hack` directory :sweat_smile:

**Comment by TimJones** [comment]
In that case, wouldn't it make more sense to update the e2e tests to consume these as modules and set up the terraform backend there directly?

**Comment by frezbo** [comment]
> In that case, wouldn't it make more sense to update the e2e tests to consume these as modules and set up the terraform backend there directly?

trying to avoid adding tf code in talos repo

**Review by TimJones — APPROVED** [review]

**Pull request merged**
