### PR TITLE
feat: add an example for Talos on OCI

### PR DESCRIPTION
**Pull request by BobyMCbobs**
adds example Terraform code and documentation to deploy Talos on Oracle Cloud

### CODE REVIEW

**Comment by smira** [comment]
Is it based in any way on https://github.com/sergelogvinov/terraform-talos/tree/main/oracle ?

**Comment by BobyMCbobs** [comment]
> Is it based in any way on https://github.com/sergelogvinov/terraform-talos/tree/main/oracle ?

@smira, it's distinct but was used as a vague reference.
This PR is following up @rothgar's request to add the generic version of the Terraform from our project here

**Review by rothgar — APPROVED** [review]
This looks like a good place to get people started to modify and build their own

**Comment by BobyMCbobs** [comment]
Just made some tweaks based on recent usage. Ready for approve and merge when you're ready 🚀

**Comment by smira** [comment]
I can't re-sign your PR, as it was made from an organization fork, I will close this one and re-push.

**Comment by smira** [comment]
Re-created as #55

**Pull request closed without merging**
